services:
    frontend:
        container_name: search-pokemon
        build: './'
        volumes:
            - '.:/app'
            - '/app/node_modules'
            - '/app/.next'
        ports:
            - 3000:3000
        environment:
            - CHOKIDAR_USEPOLLING=true
            - WATCHPACK_POLLING=true
            - TZ=Asia/Bangkok
        stdin_open: true
        tty: true